### ISSUE TITLE
Doesn't work with Faraday 0.8.0

### ISSUE THREAD

**Issue by parreirat** [nozpheratu/agilecrm-wrapper#1]
Hey. 

Was using your gem on a project, just wanted to let you know that it won't work with Faraday 0.8.0 Might want to list it on the gemspec.
Upgrading Faraday to 0.9.0 fixes it.

The error: 

```
[28] pry(main)> AgileCRMWrapper::Contact.all
NoMethodError: undefined method `status' for #<Hash:0x0000011655e5f8>
from /Users/PrettyPC/.rvm/gems/ruby-2.1.3@backend-saas/gems/agilecrm-wrapper-1.0.0/lib/agilecrm-            wrapper/response/raise_error.rb:10:in `on_complete'
```
